apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-cluster-config
  namespace: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}
  labels:
{{ include "teleport.labels" . | indent 4 }}
data:
  teleport.yaml: |
    teleport:
      log:
        output: {{ .Values.config.teleport.log.output }}
        severity: {{ .Values.config.teleport.log.severity }}
      data_dir: {{ .Values.config.teleport.data_dir }}
      storage:
        type: {{ .Values.config.teleport.storage.type }}

    auth_service:
      enabled: {{ .Values.config.auth_service.enabled }}
      license_file: {{ .Values.license.mountPath }}/license.pem
      authentication:
        type: {{ .Values.config.auth_service.authentication.type }}
      public_addr: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}.{{ .Values.cloudflare.domain }}:3025
      cluster_name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}.{{ .Values.cloudflare.domain }}

    ssh_service:
      enabled: no

    proxy_service:
      enabled: {{ .Values.config.proxy_service.enabled }}
      public_addr: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}.{{ .Values.cloudflare.domain }}
      web_listen_addr: {{ tpl .Values.config.proxy_service.web_listen_addr . }}
      listen_addr: {{ tpl .Values.config.proxy_service.listen_addr . }}
      {{- if .Values.proxy.tls.enabled }}
      https_key_file: /var/lib/certs/privkey.pem
      https_cert_file: /var/lib/certs/fullchain.pem
      {{- end }}
      kubernetes:
        enabled: {{ .Values.config.proxy_service.kubernetes.enabled }}
        listen_addr: {{ tpl .Values.config.proxy_service.kubernetes.listen_addr . }}
        {{- if .Values.config.proxy_service.kubernetes.public_addr }}
        public_addr: {{ .Values.config.teleport.kubernetes.public_addr }}
        {{- end }}
  oidc.yaml: |
    kind: oidc
    version: v2
    metadata:
      name: {{ .Values.auth0.oidc_connector_name }}
    spec:
      display: {{ .Values.auth0.display }}
      issuer_url: {{ .Values.auth0.issuer_url }}
      client_id: {{ .Values.secrets.auth0.client_id }}
      client_secret: {{ .Values.secrets.auth0.client_secret }}
      redirect_url: https://{{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}.{{ .Values.cloudflare.domain }}:{{ .Values.ports.auth.proxyweb.containerPort }}/v1/webapi/oidc/callback

      scope: {{ .Values.auth0.scope }}

      # TODO figure out a way to make this map properly from the values.yaml file
      claims_to_roles:
        - { claim: "roles", value: "gravitational/admins", roles: ["admin"] }
        - { claim: "roles", value: "gravitational/devc", roles: ["admin"] }

{{- $root := . -}}
{{- range .Values.extraClusterNames }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "teleport.fullname" $root }}-{{ . }}-cluster-config
  namespace: {{ template "teleport.fullname" $root }}-{{ . }}
  labels:
{{ include "teleport.labels" $root | indent 4 }}
data:
  teleport.yaml: |
    teleport:
      log:
        output: {{ $root.Values.config.teleport.log.output }}
        severity: {{ $root.Values.config.teleport.log.severity }}
      data_dir: {{ $root.Values.config.teleport.data_dir }}
      storage:
        type: {{ $root.Values.config.teleport.storage.type }}

    auth_service:
      enabled: {{ $root.Values.config.auth_service.enabled }}
      license_file: /var/lib/license/license.pem
      authentication:
        type: {{ $root.Values.config.auth_service.authentication.type }}
      public_addr: {{ template "teleport.fullname" $root }}-{{ . }}.{{ $root.Values.cloudflare.domain }}:3025
      cluster_name: {{ template "teleport.fullname" $root }}-{{ . }}.{{ $root.Values.cloudflare.domain }}

    ssh_service:
      enabled: no

    proxy_service:
      enabled: {{ $root.Values.config.proxy_service.enabled }}
      public_addr: {{ template "teleport.fullname" $root }}-{{ . }}.{{ $root.Values.cloudflare.domain }}
      web_listen_addr: {{ tpl $root.Values.config.proxy_service.web_listen_addr $root }}
      listen_addr: {{ tpl $root.Values.config.proxy_service.listen_addr $root }}
      {{- if $root.Values.proxy.tls.enabled }}
      https_key_file: /var/lib/certs/privkey.pem
      https_cert_file: /var/lib/certs/fullchain.pem
      {{- end }}
      kubernetes:
        enabled: {{ $root.Values.config.proxy_service.kubernetes.enabled }}
        listen_addr: {{ tpl $root.Values.config.proxy_service.kubernetes.listen_addr $root }}
        {{- if $root.Values.config.proxy_service.kubernetes.public_addr }}
        public_addr: {{ $root.Values.config.teleport.kubernetes.public_addr }}
        {{- end }}
  trusted_cluster.yaml: |
    kind: trusted_cluster
    version: v2
    metadata:
      name: {{ template "teleport.fullname" $root }}-{{ $root.Values.mainClusterName }}.{{ $root.Values.cloudflare.domain }}
    spec:
      enabled: true
      token: TRUSTEDCLUSTER_JOIN_TOKEN_PLACEHOLDER
      tunnel_addr: {{ template "teleport.fullname" $root }}-{{ $root.Values.mainClusterName }}.{{ $root.Values.cloudflare.domain }}:{{ $root.Values.ports.auth.proxytunnel.containerPort }}
      web_proxy_addr: {{ template "teleport.fullname" $root }}-{{ $root.Values.mainClusterName }}.{{ $root.Values.cloudflare.domain }}:{{ $root.Values.ports.auth.proxyweb.containerPort }}
      {{- if $root.Values.license.enabled }}
      role_map:
      - remote: "admin"
        local: ["admin"]
      {{- end }}
  oidc.yaml: |
    kind: oidc
    version: v2
    metadata:
      name: {{ $root.Values.auth0.oidc_connector_name }}
    spec:
      display: {{ $root.Values.auth0.display }}
      issuer_url: {{ $root.Values.auth0.issuer_url }}
      client_id: {{ $root.Values.secrets.auth0.client_id }}
      client_secret: {{ $root.Values.secrets.auth0.client_secret }}
      redirect_url: https://{{ template "teleport.fullname" $root }}-{{ . }}.{{ $root.Values.cloudflare.domain }}:{{ $root.Values.ports.auth.proxyweb.containerPort }}/v1/webapi/oidc/callback

      scope: {{ $root.Values.auth0.scope }}

      # TODO figure out a way to make this map properly from the values.yaml file
      claims_to_roles:
        - { claim: "roles", value: "gravitational/admins", roles: ["admin"] }
        - { claim: "roles", value: "gravitational/devc", roles: ["admin"] }
{{- end }}
