apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "teleport.fullname" . }}-cluster-config
  labels:
{{ include "teleport.labels" . | indent 4 }}
data:
  teleport.yaml: |
     teleport:
       log:
         output: {{ .Values.config.teleport.log.output }}
         severity: {{ .Values.config.teleport.log.severity }}
       data_dir: {{ .Values.config.teleport.data_dir }}
       storage:
         type: {{ .Values.config.teleport.storage.type }}

     auth_service:
       enabled: {{ .Values.config.auth_service.enabled }}
       license_file: /var/lib/license/license-enterprise.pem
       authentication:
         type: {{ .Values.config.auth_service.authentication.type }}
       public_addr: {{ .Values.clusterHostname }}:3025
       cluster_name: {{ .Values.mainClusterName }}

     ssh_service:
       enabled: no

     proxy_service:
       enabled: {{ .Values.config.proxy_service.enabled }}
       public_addr: {{ .Values.clusterHostname }}
       web_listen_addr: {{ tpl .Values.config.proxy_service.web_listen_addr . }}
       listen_addr: {{ tpl .Values.config.proxy_service.listen_addr . }}
       {{- if .Values.proxy.tls.enabled }}
       https_key_file: /var/lib/certs/tls.key
       https_cert_file: /var/lib/certs/tls.crt
       {{- end }}
       kubernetes:
         enabled: {{ .Values.config.proxy_service.kubernetes.enabled }}
         listen_addr: {{ tpl .Values.config.proxy_service.kubernetes.listen_addr . }}
         {{- if .Values.config.proxy_service.kubernetes.public_addr }}
         public_addr: {{ .Values.config.teleport.kubernetes.public_addr }}
         {{- end }}
