---
kind: Job
apiVersion: batch/v1
metadata:
  name: {{ template "teleport.fullname" .}}-secret-cleaner
  labels:
{{ include "teleport.labels" . | indent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      labels:
        app: {{ template "teleport.fullname" .}}-secret-cleaner
    spec:
      containers:
      - name: {{ .Chart.Name }}-secret-cleaner
        image: {{ .Values.secretcleaner.image.repository }}:{{ .Values.secretcleaner.image.tag }}
        imagePullPolicy: {{ .Values.secretcleaner.image.pullPolicy }}
        args:
          - {{ .Values.mainClusterName }}-node-join-token
          - {{ .Values.mainClusterName }}-trustedcluster-join-token
          - {{ .Values.mainClusterName }}-ca
          - {{ .Values.mainClusterName }}-ca-pin
      restartPolicy: Never
{{- if .Values.secretcleaner.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.secretcleaner.image.pullSecrets | indent 6 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
{{- end }}
      serviceAccountName: {{ template "teleport.serviceAccountName" . }}
  backoffLimit: 0