apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.mainClusterName }}
  labels:
{{ include "teleport.labels" .| indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-10"

{{- $root := . -}}
{{- range .Values.extraClusterNames }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
{{ include "teleport.labels" $root | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-10"
{{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: namespace-cleaner
  namespace: default
  labels:
{{ include "teleport.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      namespace: default
      labels:
        app: namespace-cleaner
    spec:
      containers:
      - name: namespace-cleaner
        image: {{ .Values.namespacecleaner.image.repository }}:{{ .Values.namespacecleaner.image.tag }}
        imagePullPolicy: {{ .Values.namespacecleaner.image.pullPolicy }}
        args:
        - {{ .Values.mainClusterName }}
        {{- range .Values.extraClusterNames }}
        - {{ . }}
        {{- end }}
      restartPolicy: Never
{{- if .Values.cloudflareagent.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.cloudflareagent.image.pullSecrets | indent 6 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
{{- end }}
      serviceAccountName: {{ template "teleport.serviceAccountName" . }}-nscleaner
  backoffLimit: 0