{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "teleport.serviceAccountName" . }}-nscleaner
  labels:
{{ include "teleport.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "teleport.serviceAccountName" . }}-{{ .Values.mainClusterName }}
  namespace: {{ .Values.mainClusterName }}
  labels:
{{ include "teleport.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "before-hook-creation"

{{- $root := . -}}
{{- range .Values.extraClusterNames }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "teleport.serviceAccountName" $root }}-{{ . }}
  namespace: {{ . }}
  labels:
{{ include "teleport.labels" $root | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
{{- end }}
{{- end -}}

